### ISSUE TITLE
コメントAPI URLの変更

### ISSUE THREAD

**Issue by Ireroku** [Midra429/ExtraCommentTools#2]
**説明**
コメントが取得されない。

**不具合を再現するための手順**
1. 通常通り動画を開く

**期待される動作**
コメントが通常通り取得される。

**環境**
不具合が発生したPCの環境
 - OS: macOS Ventura 13.6
 - ブラウザ: Firefox
 - ブラウザのバージョン: 119.0
 - 引用コメントツールのバージョン: 3.3.2
 - 種類: UserScript

**その他**
`THREAD_API`を`https://nvcomment.nicovideo.jp/v1/threads`から`https://nv-comment.nicovideo.jp/v1/threads`に変更すると動作した。
ただし、他ユーザの環境では変更されていない可能性がある。

**Comment by Ireroku** [comment]
GitHub Issueの使い方がわからず、何度も編集しています。また、私にプログラミングの経験がないため内容に誤りがあるかもしれません。すみません。

お忙しいかと思いますが、ご対応いただけると助かります。

**Comment by Midra429** [comment]
報告ありがとうございます。
v3.3.3以降で対応しました。
